apiVersion: v1
kind: Service
metadata:
  name: contoso-website
  namespace: dev
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
  selector:
    app: contoso-website
  type: ClusterIP
