apiVersion: v1
kind: Service
metadata:
  name: contoso-website-kbtg
  namespace: dev
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80      
  selector:
    app: contoso-website-kbtg
  type: ClusterIP
