apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contoso-website
  namespace: dev
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - host: contoso.aks-priv.int2skynet.com
