apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contoso-webserver
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: contoso-kbtg.aks-local.int2skynet.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: contoso-webserver
                port:
                  number: 80
